# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'akilli_kart2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1374, 779)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/rfid-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(_fromUtf8("background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:0.1 rgba(255, 255, 255, 255), stop:0.2 rgba(180, 176, 255, 167), stop:0.3 rgba(180, 151, 255, 92), stop:0.4 rgba(180, 125, 255, 51), stop:0.5 rgba(180, 76, 255, 205), stop:0.52 rgba(180, 76, 255, 205), stop:0.6 rgba(180, 180, 255, 84), stop:1 rgba(255, 255, 255, 152));"))
        MainWindow.setIconSize(QtCore.QSize(36, 36))
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(2, 2, 1031, 651))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(242, 255, 248);\n"
""))
        self.tabWidget.setIconSize(QtCore.QSize(32, 32))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 0, 1021, 601))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setAutoFillBackground(False)
        self.groupBox_7.setStyleSheet(_fromUtf8("\n"
"color: rgb(0, 170, 255);"))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.RFID_007 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_007.setGeometry(QtCore.QRect(400, 360, 21, 21))
        self.RFID_007.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_007.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/292.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RFID_007.setIcon(icon1)
        self.RFID_007.setIconSize(QtCore.QSize(32, 32))
        self.RFID_007.setAutoDefault(True)
        self.RFID_007.setDefault(True)
        self.RFID_007.setFlat(False)
        self.RFID_007.setObjectName(_fromUtf8("RFID_007"))
        self.RFID_001 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_001.setGeometry(QtCore.QRect(40, 510, 21, 21))
        self.RFID_001.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_001.setText(_fromUtf8(""))
        self.RFID_001.setIcon(icon1)
        self.RFID_001.setIconSize(QtCore.QSize(32, 32))
        self.RFID_001.setAutoDefault(True)
        self.RFID_001.setDefault(True)
        self.RFID_001.setFlat(False)
        self.RFID_001.setObjectName(_fromUtf8("RFID_001"))
        self.RFID_012 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_012.setGeometry(QtCore.QRect(520, 280, 20, 21))
        self.RFID_012.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_012.setText(_fromUtf8(""))
        self.RFID_012.setIcon(icon1)
        self.RFID_012.setIconSize(QtCore.QSize(32, 32))
        self.RFID_012.setAutoDefault(True)
        self.RFID_012.setDefault(True)
        self.RFID_012.setFlat(False)
        self.RFID_012.setObjectName(_fromUtf8("RFID_012"))
        self.RFID_006 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_006.setGeometry(QtCore.QRect(270, 520, 21, 21))
        self.RFID_006.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_006.setText(_fromUtf8(""))
        self.RFID_006.setIcon(icon1)
        self.RFID_006.setIconSize(QtCore.QSize(32, 32))
        self.RFID_006.setAutoDefault(True)
        self.RFID_006.setDefault(True)
        self.RFID_006.setFlat(False)
        self.RFID_006.setObjectName(_fromUtf8("RFID_006"))
        self.RFID_009 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_009.setGeometry(QtCore.QRect(490, 340, 20, 21))
        self.RFID_009.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_009.setText(_fromUtf8(""))
        self.RFID_009.setIcon(icon1)
        self.RFID_009.setIconSize(QtCore.QSize(32, 32))
        self.RFID_009.setAutoDefault(True)
        self.RFID_009.setDefault(True)
        self.RFID_009.setFlat(False)
        self.RFID_009.setObjectName(_fromUtf8("RFID_009"))
        self.RFID_004 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_004.setGeometry(QtCore.QRect(320, 166, 21, 21))
        self.RFID_004.setStyleSheet(_fromUtf8("border-radius:20px;"))
        self.RFID_004.setText(_fromUtf8(""))
        self.RFID_004.setIcon(icon1)
        self.RFID_004.setIconSize(QtCore.QSize(32, 32))
        self.RFID_004.setAutoDefault(True)
        self.RFID_004.setDefault(True)
        self.RFID_004.setFlat(False)
        self.RFID_004.setObjectName(_fromUtf8("RFID_004"))
        self.RFID_010 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_010.setGeometry(QtCore.QRect(520, 399, 20, 21))
        self.RFID_010.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_010.setText(_fromUtf8(""))
        self.RFID_010.setIcon(icon1)
        self.RFID_010.setIconSize(QtCore.QSize(32, 32))
        self.RFID_010.setAutoDefault(True)
        self.RFID_010.setDefault(True)
        self.RFID_010.setFlat(False)
        self.RFID_010.setObjectName(_fromUtf8("RFID_010"))
        self.RFID_013 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_013.setGeometry(QtCore.QRect(640, 370, 21, 21))
        self.RFID_013.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_013.setText(_fromUtf8(""))
        self.RFID_013.setIcon(icon1)
        self.RFID_013.setIconSize(QtCore.QSize(32, 32))
        self.RFID_013.setAutoDefault(True)
        self.RFID_013.setDefault(True)
        self.RFID_013.setFlat(False)
        self.RFID_013.setObjectName(_fromUtf8("RFID_013"))
        self.RFID_002 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_002.setGeometry(QtCore.QRect(100, 310, 21, 21))
        self.RFID_002.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_002.setText(_fromUtf8(""))
        self.RFID_002.setIcon(icon1)
        self.RFID_002.setIconSize(QtCore.QSize(32, 32))
        self.RFID_002.setAutoDefault(True)
        self.RFID_002.setDefault(True)
        self.RFID_002.setFlat(False)
        self.RFID_002.setObjectName(_fromUtf8("RFID_002"))
        self.RFID_011 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_011.setGeometry(QtCore.QRect(400, 260, 31, 21))
        self.RFID_011.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_011.setText(_fromUtf8(""))
        self.RFID_011.setIcon(icon1)
        self.RFID_011.setIconSize(QtCore.QSize(32, 32))
        self.RFID_011.setAutoDefault(True)
        self.RFID_011.setDefault(True)
        self.RFID_011.setFlat(False)
        self.RFID_011.setObjectName(_fromUtf8("RFID_011"))
        self.RFID_005 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_005.setGeometry(QtCore.QRect(260, 370, 21, 21))
        self.RFID_005.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_005.setText(_fromUtf8(""))
        self.RFID_005.setIcon(icon1)
        self.RFID_005.setIconSize(QtCore.QSize(32, 32))
        self.RFID_005.setAutoDefault(True)
        self.RFID_005.setDefault(True)
        self.RFID_005.setFlat(False)
        self.RFID_005.setObjectName(_fromUtf8("RFID_005"))
        self.RFID_008 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_008.setGeometry(QtCore.QRect(350, 530, 21, 21))
        self.RFID_008.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_008.setText(_fromUtf8(""))
        self.RFID_008.setIcon(icon1)
        self.RFID_008.setIconSize(QtCore.QSize(32, 32))
        self.RFID_008.setAutoDefault(True)
        self.RFID_008.setDefault(True)
        self.RFID_008.setFlat(False)
        self.RFID_008.setObjectName(_fromUtf8("RFID_008"))
        self.RFID_003 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_003.setGeometry(QtCore.QRect(190, 140, 21, 21))
        self.RFID_003.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_003.setText(_fromUtf8(""))
        self.RFID_003.setIcon(icon1)
        self.RFID_003.setIconSize(QtCore.QSize(32, 32))
        self.RFID_003.setAutoDefault(True)
        self.RFID_003.setDefault(True)
        self.RFID_003.setFlat(False)
        self.RFID_003.setObjectName(_fromUtf8("RFID_003"))
        self.btn_camera = QtGui.QPushButton(self.groupBox_7)
        self.btn_camera.setGeometry(QtCore.QRect(660, 370, 31, 21))
        self.btn_camera.setStyleSheet(_fromUtf8(""))
        self.btn_camera.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/Security-Camera-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_camera.setIcon(icon2)
        self.btn_camera.setIconSize(QtCore.QSize(32, 32))
        self.btn_camera.setObjectName(_fromUtf8("btn_camera"))
        self.btn_guv_oda = QtGui.QPushButton(self.groupBox_7)
        self.btn_guv_oda.setGeometry(QtCore.QRect(620, 440, 31, 31))
        self.btn_guv_oda.setStyleSheet(_fromUtf8(""))
        self.btn_guv_oda.setText(_fromUtf8(""))
        self.btn_guv_oda.setIcon(icon2)
        self.btn_guv_oda.setIconSize(QtCore.QSize(32, 32))
        self.btn_guv_oda.setObjectName(_fromUtf8("btn_guv_oda"))
        self.btn_kablo3 = QtGui.QPushButton(self.groupBox_7)
        self.btn_kablo3.setGeometry(QtCore.QRect(590, 400, 31, 21))
        self.btn_kablo3.setStyleSheet(_fromUtf8(""))
        self.btn_kablo3.setText(_fromUtf8(""))
        self.btn_kablo3.setIcon(icon2)
        self.btn_kablo3.setIconSize(QtCore.QSize(32, 32))
        self.btn_kablo3.setObjectName(_fromUtf8("btn_kablo3"))
        self.btn_kablo2 = QtGui.QPushButton(self.groupBox_7)
        self.btn_kablo2.setGeometry(QtCore.QRect(370, 400, 31, 31))
        self.btn_kablo2.setStyleSheet(_fromUtf8(""))
        self.btn_kablo2.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/Security-sag.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_kablo2.setIcon(icon3)
        self.btn_kablo2.setIconSize(QtCore.QSize(32, 32))
        self.btn_kablo2.setObjectName(_fromUtf8("btn_kablo2"))
        self.btn_kablo1 = QtGui.QPushButton(self.groupBox_7)
        self.btn_kablo1.setGeometry(QtCore.QRect(370, 530, 31, 31))
        self.btn_kablo1.setStyleSheet(_fromUtf8(""))
        self.btn_kablo1.setText(_fromUtf8(""))
        self.btn_kablo1.setIcon(icon3)
        self.btn_kablo1.setIconSize(QtCore.QSize(32, 32))
        self.btn_kablo1.setObjectName(_fromUtf8("btn_kablo1"))
        self.btn_kablaj_kalite = QtGui.QPushButton(self.groupBox_7)
        self.btn_kablaj_kalite.setGeometry(QtCore.QRect(280, 550, 31, 21))
        self.btn_kablaj_kalite.setStyleSheet(_fromUtf8(""))
        self.btn_kablaj_kalite.setText(_fromUtf8(""))
        self.btn_kablaj_kalite.setIcon(icon3)
        self.btn_kablaj_kalite.setIconSize(QtCore.QSize(32, 32))
        self.btn_kablaj_kalite.setObjectName(_fromUtf8("btn_kablaj_kalite"))
        self.btn_uretim1 = QtGui.QPushButton(self.groupBox_7)
        self.btn_uretim1.setGeometry(QtCore.QRect(250, 550, 31, 21))
        self.btn_uretim1.setStyleSheet(_fromUtf8(""))
        self.btn_uretim1.setText(_fromUtf8(""))
        self.btn_uretim1.setIcon(icon2)
        self.btn_uretim1.setIconSize(QtCore.QSize(32, 32))
        self.btn_uretim1.setObjectName(_fromUtf8("btn_uretim1"))
        self.btn_depo1 = QtGui.QPushButton(self.groupBox_7)
        self.btn_depo1.setGeometry(QtCore.QRect(120, 280, 31, 31))
        self.btn_depo1.setStyleSheet(_fromUtf8(""))
        self.btn_depo1.setText(_fromUtf8(""))
        self.btn_depo1.setIcon(icon2)
        self.btn_depo1.setIconSize(QtCore.QSize(32, 32))
        self.btn_depo1.setObjectName(_fromUtf8("btn_depo1"))
        self.btn_depo2 = QtGui.QPushButton(self.groupBox_7)
        self.btn_depo2.setGeometry(QtCore.QRect(100, 160, 31, 31))
        self.btn_depo2.setStyleSheet(_fromUtf8(""))
        self.btn_depo2.setText(_fromUtf8(""))
        self.btn_depo2.setIcon(icon2)
        self.btn_depo2.setIconSize(QtCore.QSize(32, 32))
        self.btn_depo2.setObjectName(_fromUtf8("btn_depo2"))
        self.btn_idari1 = QtGui.QPushButton(self.groupBox_7)
        self.btn_idari1.setGeometry(QtCore.QRect(820, 530, 31, 31))
        self.btn_idari1.setStyleSheet(_fromUtf8(""))
        self.btn_idari1.setText(_fromUtf8(""))
        self.btn_idari1.setIcon(icon2)
        self.btn_idari1.setIconSize(QtCore.QSize(32, 32))
        self.btn_idari1.setObjectName(_fromUtf8("btn_idari1"))
        self.btn_idari2 = QtGui.QPushButton(self.groupBox_7)
        self.btn_idari2.setGeometry(QtCore.QRect(900, 210, 31, 31))
        self.btn_idari2.setStyleSheet(_fromUtf8(""))
        self.btn_idari2.setText(_fromUtf8(""))
        self.btn_idari2.setIcon(icon2)
        self.btn_idari2.setIconSize(QtCore.QSize(32, 32))
        self.btn_idari2.setObjectName(_fromUtf8("btn_idari2"))
        self.btn_lab = QtGui.QPushButton(self.groupBox_7)
        self.btn_lab.setGeometry(QtCore.QRect(660, 160, 31, 21))
        self.btn_lab.setStyleSheet(_fromUtf8(""))
        self.btn_lab.setText(_fromUtf8(""))
        self.btn_lab.setIcon(icon2)
        self.btn_lab.setIconSize(QtCore.QSize(32, 32))
        self.btn_lab.setObjectName(_fromUtf8("btn_lab"))
        self.btn_uretim2 = QtGui.QPushButton(self.groupBox_7)
        self.btn_uretim2.setGeometry(QtCore.QRect(140, 150, 31, 21))
        self.btn_uretim2.setStyleSheet(_fromUtf8(""))
        self.btn_uretim2.setText(_fromUtf8(""))
        self.btn_uretim2.setIcon(icon3)
        self.btn_uretim2.setIconSize(QtCore.QSize(32, 32))
        self.btn_uretim2.setObjectName(_fromUtf8("btn_uretim2"))
        self.btn_giris = QtGui.QPushButton(self.groupBox_7)
        self.btn_giris.setGeometry(QtCore.QRect(730, 300, 31, 21))
        self.btn_giris.setStyleSheet(_fromUtf8(""))
        self.btn_giris.setText(_fromUtf8(""))
        self.btn_giris.setIcon(icon2)
        self.btn_giris.setIconSize(QtCore.QSize(32, 32))
        self.btn_giris.setObjectName(_fromUtf8("btn_giris"))
        self.btn_cay = QtGui.QPushButton(self.groupBox_7)
        self.btn_cay.setGeometry(QtCore.QRect(730, 240, 31, 21))
        self.btn_cay.setStyleSheet(_fromUtf8(""))
        self.btn_cay.setText(_fromUtf8(""))
        self.btn_cay.setIcon(icon2)
        self.btn_cay.setIconSize(QtCore.QSize(32, 32))
        self.btn_cay.setObjectName(_fromUtf8("btn_cay"))
        self.btn_turnike = QtGui.QPushButton(self.groupBox_7)
        self.btn_turnike.setGeometry(QtCore.QRect(690, 490, 31, 21))
        self.btn_turnike.setStyleSheet(_fromUtf8(""))
        self.btn_turnike.setText(_fromUtf8(""))
        self.btn_turnike.setIcon(icon2)
        self.btn_turnike.setIconSize(QtCore.QSize(32, 32))
        self.btn_turnike.setObjectName(_fromUtf8("btn_turnike"))
        self.RFID_014 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_014.setGeometry(QtCore.QRect(815, 512, 21, 21))
        self.RFID_014.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_014.setText(_fromUtf8(""))
        self.RFID_014.setIcon(icon1)
        self.RFID_014.setIconSize(QtCore.QSize(32, 32))
        self.RFID_014.setAutoDefault(True)
        self.RFID_014.setDefault(True)
        self.RFID_014.setFlat(False)
        self.RFID_014.setObjectName(_fromUtf8("RFID_014"))
        self.RFID_015 = QtGui.QPushButton(self.groupBox_7)
        self.RFID_015.setGeometry(QtCore.QRect(740, 260, 21, 21))
        self.RFID_015.setStyleSheet(_fromUtf8("border-radius: 10px;"))
        self.RFID_015.setText(_fromUtf8(""))
        self.RFID_015.setIcon(icon1)
        self.RFID_015.setIconSize(QtCore.QSize(32, 32))
        self.RFID_015.setAutoDefault(True)
        self.RFID_015.setDefault(True)
        self.RFID_015.setFlat(False)
        self.RFID_015.setObjectName(_fromUtf8("RFID_015"))
        self.btn_kose = QtGui.QPushButton(self.groupBox_7)
        self.btn_kose.setGeometry(QtCore.QRect(140, 40, 31, 31))
        self.btn_kose.setStyleSheet(_fromUtf8(""))
        self.btn_kose.setText(_fromUtf8(""))
        self.btn_kose.setIcon(icon3)
        self.btn_kose.setIconSize(QtCore.QSize(32, 32))
        self.btn_kose.setObjectName(_fromUtf8("btn_kose"))
        self.label_11 = QtGui.QLabel(self.groupBox_7)
        self.label_11.setGeometry(QtCore.QRect(0, 20, 1021, 581))
        self.label_11.setText(_fromUtf8(""))
        self.label_11.setPixmap(QtGui.QPixmap(_fromUtf8(":/w/htr_.jpg")))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.btn_otopark = QtGui.QPushButton(self.groupBox_7)
        self.btn_otopark.setGeometry(QtCore.QRect(740, 570, 31, 21))
        self.btn_otopark.setStyleSheet(_fromUtf8(""))
        self.btn_otopark.setText(_fromUtf8(""))
        self.btn_otopark.setIcon(icon2)
        self.btn_otopark.setIconSize(QtCore.QSize(32, 32))
        self.btn_otopark.setObjectName(_fromUtf8("btn_otopark"))
        self.btn_yan = QtGui.QPushButton(self.groupBox_7)
        self.btn_yan.setGeometry(QtCore.QRect(0, 480, 31, 21))
        self.btn_yan.setStyleSheet(_fromUtf8(""))
        self.btn_yan.setText(_fromUtf8(""))
        self.btn_yan.setIcon(icon3)
        self.btn_yan.setIconSize(QtCore.QSize(32, 32))
        self.btn_yan.setObjectName(_fromUtf8("btn_yan"))
        self.btn_otopark_2 = QtGui.QPushButton(self.groupBox_7)
        self.btn_otopark_2.setGeometry(QtCore.QRect(740, 510, 31, 21))
        self.btn_otopark_2.setStyleSheet(_fromUtf8(""))
        self.btn_otopark_2.setText(_fromUtf8(""))
        self.btn_otopark_2.setIcon(icon2)
        self.btn_otopark_2.setIconSize(QtCore.QSize(32, 32))
        self.btn_otopark_2.setObjectName(_fromUtf8("btn_otopark_2"))
        self.label_11.raise_()
        self.btn_kablaj_kalite.raise_()
        self.btn_kablo1.raise_()
        self.RFID_012.raise_()
        self.RFID_002.raise_()
        self.RFID_008.raise_()
        self.RFID_001.raise_()
        self.RFID_004.raise_()
        self.RFID_005.raise_()
        self.RFID_007.raise_()
        self.RFID_009.raise_()
        self.RFID_011.raise_()
        self.btn_camera.raise_()
        self.btn_guv_oda.raise_()
        self.btn_kablo3.raise_()
        self.btn_kablo2.raise_()
        self.RFID_006.raise_()
        self.btn_depo1.raise_()
        self.btn_depo2.raise_()
        self.btn_idari1.raise_()
        self.btn_idari2.raise_()
        self.btn_lab.raise_()
        self.RFID_003.raise_()
        self.RFID_010.raise_()
        self.RFID_013.raise_()
        self.btn_giris.raise_()
        self.btn_cay.raise_()
        self.btn_turnike.raise_()
        self.RFID_014.raise_()
        self.RFID_015.raise_()
        self.btn_kose.raise_()
        self.btn_uretim1.raise_()
        self.btn_uretim2.raise_()
        self.btn_otopark.raise_()
        self.btn_yan.raise_()
        self.btn_otopark_2.raise_()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/plan.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.tableWidget_5 = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_5.setGeometry(QtCore.QRect(20, 30, 781, 511))
        self.tableWidget_5.setObjectName(_fromUtf8("tableWidget_5"))
        self.tableWidget_5.setColumnCount(0)
        self.tableWidget_5.setRowCount(0)
        self.btn_ara = QtGui.QPushButton(self.tab_5)
        self.btn_ara.setGeometry(QtCore.QRect(840, 200, 181, 81))
        self.btn_ara.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/Database-Search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ara.setIcon(icon5)
        self.btn_ara.setIconSize(QtCore.QSize(52, 52))
        self.btn_ara.setObjectName(_fromUtf8("btn_ara"))
        self.groupBox = QtGui.QGroupBox(self.tab_5)
        self.groupBox.setGeometry(QtCore.QRect(840, 30, 181, 71))
        self.groupBox.setStyleSheet(_fromUtf8("font: 12pt \"Calibri\";\n"
"background-color: rgb(203, 220, 201);"))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.comboBox.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";"))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_2.setGeometry(QtCore.QRect(840, 110, 181, 71))
        self.groupBox_2.setStyleSheet(_fromUtf8("font: 12pt \"Calibri\";\n"
"background-color: rgb(203, 220, 201);"))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(10, 30, 141, 20))
        self.lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";"))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/pers.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon6, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.plot = PlotWidget(self.tab_6)
        self.plot.setGeometry(QtCore.QRect(20, 30, 781, 511))
        self.plot.setObjectName(_fromUtf8("plot"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_6)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 30, 781, 511))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.btn_stats = QtGui.QPushButton(self.tab_6)
        self.btn_stats.setGeometry(QtCore.QRect(840, 200, 181, 81))
        self.btn_stats.setText(_fromUtf8(""))
        self.btn_stats.setIcon(icon5)
        self.btn_stats.setIconSize(QtCore.QSize(52, 52))
        self.btn_stats.setObjectName(_fromUtf8("btn_stats"))
        self.groupBox_16 = QtGui.QGroupBox(self.tab_6)
        self.groupBox_16.setGeometry(QtCore.QRect(840, 30, 181, 71))
        self.groupBox_16.setStyleSheet(_fromUtf8("font: 12pt \"Calibri\";\n"
"background-color: rgb(203, 220, 201);"))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.stats_combo = QtGui.QComboBox(self.groupBox_16)
        self.stats_combo.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.stats_combo.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";"))
        self.stats_combo.setObjectName(_fromUtf8("stats_combo"))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/stats.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_6, icon7, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tableWidget = QtGui.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 781, 511))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.btn_iptal = QtGui.QPushButton(self.tab_2)
        self.btn_iptal.setGeometry(QtCore.QRect(840, 300, 181, 71))
        self.btn_iptal.setStyleSheet(_fromUtf8(""))
        self.btn_iptal.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/minus.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_iptal.setIcon(icon8)
        self.btn_iptal.setIconSize(QtCore.QSize(48, 48))
        self.btn_iptal.setObjectName(_fromUtf8("btn_iptal"))
        self.label_30 = QtGui.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(870, 390, 32, 19))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.tab_2)
        self.label_31.setGeometry(QtCore.QRect(850, 390, 17, 19))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.btn_eslesme_ara = QtGui.QPushButton(self.tab_2)
        self.btn_eslesme_ara.setGeometry(QtCore.QRect(840, 200, 181, 81))
        self.btn_eslesme_ara.setText(_fromUtf8(""))
        self.btn_eslesme_ara.setIcon(icon5)
        self.btn_eslesme_ara.setIconSize(QtCore.QSize(52, 52))
        self.btn_eslesme_ara.setObjectName(_fromUtf8("btn_eslesme_ara"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(840, 30, 181, 71))
        self.groupBox_4.setStyleSheet(_fromUtf8("font: 12pt \"Calibri\";\n"
"background-color: rgb(170, 255, 127);"))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.comboBox_3 = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.comboBox_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";"))
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(840, 110, 181, 71))
        self.groupBox_6.setStyleSheet(_fromUtf8("font: 12pt \"Calibri\";\n"
"background-color: rgb(170, 255, 127);"))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 30, 141, 20))
        self.lineEdit_3.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";"))
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/match.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon9, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tableWidget_3 = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(20, 30, 781, 511))
        self.tableWidget_3.setObjectName(_fromUtf8("tableWidget_3"))
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(840, 30, 181, 71))
        self.groupBox_3.setStyleSheet(_fromUtf8("font: 12pt \"Calibri\";\n"
"background-color: rgb(170, 255, 127);"))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.comboBox_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";"))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(840, 110, 181, 71))
        self.groupBox_5.setStyleSheet(_fromUtf8("font: 12pt \"Calibri\";\n"
"background-color: rgb(170, 255, 127);"))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 30, 141, 20))
        self.lineEdit_2.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";"))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.btn_kamera_ara = QtGui.QPushButton(self.tab_3)
        self.btn_kamera_ara.setGeometry(QtCore.QRect(840, 200, 181, 81))
        self.btn_kamera_ara.setText(_fromUtf8(""))
        self.btn_kamera_ara.setIcon(icon5)
        self.btn_kamera_ara.setIconSize(QtCore.QSize(52, 52))
        self.btn_kamera_ara.setObjectName(_fromUtf8("btn_kamera_ara"))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/video-512.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon10, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.tableWidget_4 = QtGui.QTableWidget(self.tab_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(20, 30, 781, 511))
        self.tableWidget_4.setObjectName(_fromUtf8("tableWidget_4"))
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.btn_rfid_ara = QtGui.QPushButton(self.tab_4)
        self.btn_rfid_ara.setGeometry(QtCore.QRect(840, 200, 181, 81))
        self.btn_rfid_ara.setText(_fromUtf8(""))
        self.btn_rfid_ara.setIcon(icon5)
        self.btn_rfid_ara.setIconSize(QtCore.QSize(52, 52))
        self.btn_rfid_ara.setObjectName(_fromUtf8("btn_rfid_ara"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_9.setGeometry(QtCore.QRect(840, 110, 181, 71))
        self.groupBox_9.setStyleSheet(_fromUtf8("font: 12pt \"Calibri\";\n"
"background-color: rgb(170, 255, 127);"))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 30, 141, 20))
        self.lineEdit_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";"))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_10.setGeometry(QtCore.QRect(840, 30, 181, 71))
        self.groupBox_10.setStyleSheet(_fromUtf8("font: 12pt \"Calibri\";\n"
"background-color: rgb(170, 255, 127);"))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.comboBox_4 = QtGui.QComboBox(self.groupBox_10)
        self.comboBox_4.setGeometry(QtCore.QRect(10, 30, 141, 21))
        self.comboBox_4.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Calibri\";"))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/rf.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon11, _fromUtf8(""))
        self.groupBox_8 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(4, 657, 211, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(243, 255, 251))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_8.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setStyleSheet(_fromUtf8("background-color: rgb(243, 255, 251);"))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_27 = QtGui.QLabel(self.groupBox_8)
        self.label_27.setGeometry(QtCore.QRect(9, 48, 61, 21))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_25 = QtGui.QLabel(self.groupBox_8)
        self.label_25.setGeometry(QtCore.QRect(17, 23, 31, 31))
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setPixmap(QtGui.QPixmap(_fromUtf8(":/w/Security-sag.png")))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_29 = QtGui.QLabel(self.groupBox_8)
        self.label_29.setGeometry(QtCore.QRect(57, 48, 81, 21))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_34 = QtGui.QLabel(self.groupBox_8)
        self.label_34.setGeometry(QtCore.QRect(74, 20, 31, 31))
        self.label_34.setText(_fromUtf8(""))
        self.label_34.setPixmap(QtGui.QPixmap(_fromUtf8(":/w/292.png")))
        self.label_34.setScaledContents(True)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_36 = QtGui.QLabel(self.groupBox_8)
        self.label_36.setGeometry(QtCore.QRect(136, 48, 71, 21))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_37 = QtGui.QLabel(self.groupBox_8)
        self.label_37.setGeometry(QtCore.QRect(150, 22, 31, 31))
        self.label_37.setText(_fromUtf8(""))
        self.label_37.setPixmap(QtGui.QPixmap(_fromUtf8(":/w/target_red2.png")))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_27.raise_()
        self.label_25.raise_()
        self.label_34.raise_()
        self.label_29.raise_()
        self.label_36.raise_()
        self.label_37.raise_()
        self.btn_exit = QtGui.QPushButton(self.centralwidget)
        self.btn_exit.setGeometry(QtCore.QRect(955, 657, 75, 71))
        self.btn_exit.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_exit.setIcon(icon12)
        self.btn_exit.setIconSize(QtCore.QSize(48, 48))
        self.btn_exit.setObjectName(_fromUtf8("btn_exit"))
        self.groupBox_11 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_11.setGeometry(QtCore.QRect(1034, 32, 331, 271))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.frame = QtGui.QFrame(self.groupBox_11)
        self.frame.setGeometry(QtCore.QRect(4, 20, 321, 251))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.groupBox_12 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_12.setGeometry(QtCore.QRect(1040, 440, 326, 281))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_12.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setStyleSheet(_fromUtf8("background-color: rgb(233, 255, 255);\n"
""))
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.btn_izle = QtGui.QPushButton(self.groupBox_12)
        self.btn_izle.setGeometry(QtCore.QRect(10, 230, 81, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btn_izle.setFont(font)
        self.btn_izle.setStyleSheet(_fromUtf8("font: 75  12pt \"Calibri\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(208, 205, 203);"))
        self.btn_izle.setObjectName(_fromUtf8("btn_izle"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_12)
        self.layoutWidget.setGeometry(QtCore.QRect(123, 66, 201, 141))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.cmb_personel = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.cmb_personel.setFont(font)
        self.cmb_personel.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cmb_personel.setObjectName(_fromUtf8("cmb_personel"))
        self.verticalLayout_4.addWidget(self.cmb_personel)
        self.cmb_bolum = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.cmb_bolum.setFont(font)
        self.cmb_bolum.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cmb_bolum.setObjectName(_fromUtf8("cmb_bolum"))
        self.cmb_bolum.addItem(_fromUtf8(""))
        self.cmb_bolum.addItem(_fromUtf8(""))
        self.cmb_bolum.addItem(_fromUtf8(""))
        self.cmb_bolum.addItem(_fromUtf8(""))
        self.cmb_bolum.addItem(_fromUtf8(""))
        self.cmb_bolum.addItem(_fromUtf8(""))
        self.cmb_bolum.addItem(_fromUtf8(""))
        self.cmb_bolum.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.cmb_bolum)
        self.cmb_kamera = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.cmb_kamera.setFont(font)
        self.cmb_kamera.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cmb_kamera.setObjectName(_fromUtf8("cmb_kamera"))
        self.cmb_kamera.addItem(_fromUtf8(""))
        self.cmb_kamera.addItem(_fromUtf8(""))
        self.cmb_kamera.addItem(_fromUtf8(""))
        self.cmb_kamera.addItem(_fromUtf8(""))
        self.cmb_kamera.addItem(_fromUtf8(""))
        self.cmb_kamera.addItem(_fromUtf8(""))
        self.cmb_kamera.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.cmb_kamera)
        self.cmb_okuyucu = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.cmb_okuyucu.setFont(font)
        self.cmb_okuyucu.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cmb_okuyucu.setObjectName(_fromUtf8("cmb_okuyucu"))
        self.cmb_okuyucu.addItem(_fromUtf8(""))
        self.cmb_okuyucu.addItem(_fromUtf8(""))
        self.cmb_okuyucu.addItem(_fromUtf8(""))
        self.cmb_okuyucu.addItem(_fromUtf8(""))
        self.cmb_okuyucu.addItem(_fromUtf8(""))
        self.cmb_okuyucu.addItem(_fromUtf8(""))
        self.cmb_okuyucu.addItem(_fromUtf8(""))
        self.cmb_okuyucu.addItem(_fromUtf8(""))
        self.cmb_okuyucu.addItem(_fromUtf8(""))
        self.cmb_okuyucu.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.cmb_okuyucu)
        self.cmb_ziyaretci = QtGui.QComboBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.cmb_ziyaretci.setFont(font)
        self.cmb_ziyaretci.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.cmb_ziyaretci.setObjectName(_fromUtf8("cmb_ziyaretci"))
        self.cmb_ziyaretci.addItem(_fromUtf8(""))
        self.cmb_ziyaretci.addItem(_fromUtf8(""))
        self.cmb_ziyaretci.addItem(_fromUtf8(""))
        self.cmb_ziyaretci.addItem(_fromUtf8(""))
        self.verticalLayout_4.addWidget(self.cmb_ziyaretci)
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_12)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 35, 91, 183))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.radio_hepsi = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.radio_hepsi.setFont(font)
        self.radio_hepsi.setStyleSheet(_fromUtf8("background-color: rgb(203, 220, 201);"))
        self.radio_hepsi.setObjectName(_fromUtf8("radio_hepsi"))
        self.verticalLayout_3.addWidget(self.radio_hepsi)
        self.radio_personel = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.radio_personel.setFont(font)
        self.radio_personel.setStyleSheet(_fromUtf8("background-color: rgb(203, 220, 201);"))
        self.radio_personel.setObjectName(_fromUtf8("radio_personel"))
        self.verticalLayout_3.addWidget(self.radio_personel)
        self.radio_bolum = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.radio_bolum.setFont(font)
        self.radio_bolum.setStyleSheet(_fromUtf8("background-color: rgb(203, 220, 201);"))
        self.radio_bolum.setObjectName(_fromUtf8("radio_bolum"))
        self.verticalLayout_3.addWidget(self.radio_bolum)
        self.radio_kamera = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.radio_kamera.setFont(font)
        self.radio_kamera.setStyleSheet(_fromUtf8("background-color: rgb(203, 220, 201);"))
        self.radio_kamera.setObjectName(_fromUtf8("radio_kamera"))
        self.verticalLayout_3.addWidget(self.radio_kamera)
        self.radio_okuyucu = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.radio_okuyucu.setFont(font)
        self.radio_okuyucu.setStyleSheet(_fromUtf8("background-color: rgb(203, 220, 201);"))
        self.radio_okuyucu.setObjectName(_fromUtf8("radio_okuyucu"))
        self.verticalLayout_3.addWidget(self.radio_okuyucu)
        self.radio_ziyaretci = QtGui.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.radio_ziyaretci.setFont(font)
        self.radio_ziyaretci.setStyleSheet(_fromUtf8("background-color: rgb(203, 220, 201);"))
        self.radio_ziyaretci.setObjectName(_fromUtf8("radio_ziyaretci"))
        self.verticalLayout_3.addWidget(self.radio_ziyaretci)
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox_12)
        self.groupBox_14.setGeometry(QtCore.QRect(100, 215, 221, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        font.setItalic(True)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setStyleSheet(_fromUtf8("color: rgb(0, 170, 255);"))
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.lbl_izlenen = QtGui.QLabel(self.groupBox_14)
        self.lbl_izlenen.setGeometry(QtCore.QRect(3, 20, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_izlenen.setFont(font)
        self.lbl_izlenen.setStyleSheet(_fromUtf8("background-color: rgb(155, 185,180);\n"
"color: rgb(10, 15, 255);"))
        self.lbl_izlenen.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_izlenen.setObjectName(_fromUtf8("lbl_izlenen"))
        self.groupBox_13 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_13.setGeometry(QtCore.QRect(1035, 310, 331, 121))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.groupBox_13.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setStyleSheet(_fromUtf8("background-color: rgb(233, 255, 255);\n"
"QLabel { background-color : red; color : blue; }\n"
"\n"
""))
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_13)
        self.layoutWidget2.setGeometry(QtCore.QRect(120, 20, 201, 92))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbl_canli_kisi = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_canli_kisi.setFont(font)
        self.lbl_canli_kisi.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.lbl_canli_kisi.setText(_fromUtf8(""))
        self.lbl_canli_kisi.setObjectName(_fromUtf8("lbl_canli_kisi"))
        self.verticalLayout_2.addWidget(self.lbl_canli_kisi)
        self.lbl_canli_okuyucu = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_canli_okuyucu.setFont(font)
        self.lbl_canli_okuyucu.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.lbl_canli_okuyucu.setText(_fromUtf8(""))
        self.lbl_canli_okuyucu.setObjectName(_fromUtf8("lbl_canli_okuyucu"))
        self.verticalLayout_2.addWidget(self.lbl_canli_okuyucu)
        self.lbl_canli_kamera = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_canli_kamera.setFont(font)
        self.lbl_canli_kamera.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.lbl_canli_kamera.setText(_fromUtf8(""))
        self.lbl_canli_kamera.setObjectName(_fromUtf8("lbl_canli_kamera"))
        self.verticalLayout_2.addWidget(self.lbl_canli_kamera)
        self.lbl_canli_zaman = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_canli_zaman.setFont(font)
        self.lbl_canli_zaman.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);"))
        self.lbl_canli_zaman.setText(_fromUtf8(""))
        self.lbl_canli_zaman.setObjectName(_fromUtf8("lbl_canli_zaman"))
        self.verticalLayout_2.addWidget(self.lbl_canli_zaman)
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_13)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 91, 92))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_12 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("background-color: rgb(203, 220, 201);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);\n"
"background-color: rgb(203, 220, 201);"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);\n"
"background-color: rgb(203, 220, 201);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout.addWidget(self.label_14)
        self.label_16 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(_fromUtf8("background-color: rgb(170, 255, 127);\n"
"background-color: rgb(203, 220, 201);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout.addWidget(self.label_16)
        self.lbl_durum = QtGui.QLabel(self.centralwidget)
        self.lbl_durum.setGeometry(QtCore.QRect(420, 685, 221, 21))
        self.lbl_durum.setStyleSheet(_fromUtf8("background-color: rgb(188, 240, 255);"))
        self.lbl_durum.setObjectName(_fromUtf8("lbl_durum"))
        self.btn_harita_yukle = QtGui.QPushButton(self.centralwidget)
        self.btn_harita_yukle.setGeometry(QtCore.QRect(864, 660, 81, 71))
        self.btn_harita_yukle.setStyleSheet(_fromUtf8("background-color: rgb(240, 255, 255);"))
        self.btn_harita_yukle.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/w/plann.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_harita_yukle.setIcon(icon13)
        self.btn_harita_yukle.setIconSize(QtCore.QSize(48, 48))
        self.btn_harita_yukle.setObjectName(_fromUtf8("btn_harita_yukle"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1374, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionYukle = QtGui.QAction(MainWindow)
        self.actionYukle.setObjectName(_fromUtf8("actionYukle"))

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Akilli Kart Entegrasyon", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Plan", None))
        self.btn_camera.setToolTip(_translate("MainWindow", "ÜRETİM KORİDORU", None))
        self.btn_guv_oda.setToolTip(_translate("MainWindow", "GÜVENLİKLİ ODA", None))
        self.btn_kablo3.setToolTip(_translate("MainWindow", "KABLO-3", None))
        self.btn_kablo2.setToolTip(_translate("MainWindow", "KABLO-2", None))
        self.btn_kablo1.setToolTip(_translate("MainWindow", "KABLO-1", None))
        self.btn_kablaj_kalite.setToolTip(_translate("MainWindow", "KABLAJ-KALİTE", None))
        self.btn_uretim1.setToolTip(_translate("MainWindow", "ÜRETİM-1", None))
        self.btn_depo1.setToolTip(_translate("MainWindow", "DEPO-1", None))
        self.btn_idari1.setToolTip(_translate("MainWindow", "İDARİ-1", None))
        self.btn_idari2.setToolTip(_translate("MainWindow", "İDARİ-2", None))
        self.btn_lab.setToolTip(_translate("MainWindow", "4NCÜ DERECE", None))
        self.btn_uretim2.setToolTip(_translate("MainWindow", "ÜRETİM-2", None))
        self.btn_giris.setToolTip(_translate("MainWindow", "GİRİŞ", None))
        self.btn_cay.setToolTip(_translate("MainWindow", "ÜRETİM KORİDORU", None))
        self.btn_turnike.setToolTip(_translate("MainWindow", "GİRİŞ", None))
        self.btn_kose.setToolTip(_translate("MainWindow", "ÜRETİM-2", None))
        self.btn_otopark.setToolTip(_translate("MainWindow", "GİRİŞ", None))
        self.btn_yan.setToolTip(_translate("MainWindow", "ÜRETİM-2", None))
        self.btn_otopark_2.setToolTip(_translate("MainWindow", "GİRİŞ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "YERLEŞİM PLANI", None))
        self.groupBox.setTitle(_translate("MainWindow", "Kolon", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Değer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "KAYITLAR", None))
        self.groupBox_16.setTitle(_translate("MainWindow", "Personel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "İSTATİSTİK", None))
        self.btn_iptal.setToolTip(_translate("MainWindow", "Öncelikle \"idd\" kolonundan hücre seçiniz, ardından silme işlemini deneyiniz.", None))
        self.label_30.setText(_translate("MainWindow", "____", None))
        self.label_31.setText(_translate("MainWindow", "Id:", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Kolon", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Değer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "EŞLEŞMELER", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Kolon", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Değer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "KAMERALAR", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Değer", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Kolon", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "RFID OKUYUCULAR", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Aygıtlar", None))
        self.label_27.setText(_translate("MainWindow", "Kamera", None))
        self.label_29.setText(_translate("MainWindow", "RFID Okuyucu", None))
        self.label_36.setText(_translate("MainWindow", "Seçili Okuyucu", None))
        self.groupBox_11.setTitle(_translate("MainWindow", "Akış", None))
        self.groupBox_12.setTitle(_translate("MainWindow", "İzleme", None))
        self.btn_izle.setText(_translate("MainWindow", "İZLE", None))
        self.cmb_bolum.setItemText(0, _translate("MainWindow", "<BölümSeçiniz>", None))
        self.cmb_bolum.setItemText(1, _translate("MainWindow", "Bilgi İşlem", None))
        self.cmb_bolum.setItemText(2, _translate("MainWindow", "Satın Alma", None))
        self.cmb_bolum.setItemText(3, _translate("MainWindow", "İş Geliştirme", None))
        self.cmb_bolum.setItemText(4, _translate("MainWindow", "Radar", None))
        self.cmb_bolum.setItemText(5, _translate("MainWindow", "AGS", None))
        self.cmb_bolum.setItemText(6, _translate("MainWindow", "Ar-Ge", None))
        self.cmb_bolum.setItemText(7, _translate("MainWindow", "Depo", None))
        self.cmb_kamera.setItemText(0, _translate("MainWindow", "<Kamera Seçiniz>", None))
        self.cmb_kamera.setItemText(1, _translate("MainWindow", "Üretim Koridor", None))
        self.cmb_kamera.setItemText(2, _translate("MainWindow", "Güvenlikli Oda", None))
        self.cmb_kamera.setItemText(3, _translate("MainWindow", "Üretim Holü", None))
        self.cmb_kamera.setItemText(4, _translate("MainWindow", "Depo", None))
        self.cmb_kamera.setItemText(5, _translate("MainWindow", "Giriş", None))
        self.cmb_kamera.setItemText(6, _translate("MainWindow", "İdari Birimler", None))
        self.cmb_okuyucu.setItemText(0, _translate("MainWindow", "<Okuyucu Seçiniz>", None))
        self.cmb_okuyucu.setItemText(1, _translate("MainWindow", "RFID_001", None))
        self.cmb_okuyucu.setItemText(2, _translate("MainWindow", "RFID_002", None))
        self.cmb_okuyucu.setItemText(3, _translate("MainWindow", "RFID_003", None))
        self.cmb_okuyucu.setItemText(4, _translate("MainWindow", "RFID_004", None))
        self.cmb_okuyucu.setItemText(5, _translate("MainWindow", "RFID_005", None))
        self.cmb_okuyucu.setItemText(6, _translate("MainWindow", "RFID_006", None))
        self.cmb_okuyucu.setItemText(7, _translate("MainWindow", "RFID_007", None))
        self.cmb_okuyucu.setItemText(8, _translate("MainWindow", "RFID_008", None))
        self.cmb_okuyucu.setItemText(9, _translate("MainWindow", "RFID_009", None))
        self.cmb_ziyaretci.setItemText(0, _translate("MainWindow", "<Ziyaretçi Seçiniz>", None))
        self.cmb_ziyaretci.setItemText(1, _translate("MainWindow", "Ziyaretçi-1", None))
        self.cmb_ziyaretci.setItemText(2, _translate("MainWindow", "Ziyaretçi-2", None))
        self.cmb_ziyaretci.setItemText(3, _translate("MainWindow", "Ziraretçi-3", None))
        self.radio_hepsi.setText(_translate("MainWindow", "Hepsi", None))
        self.radio_personel.setText(_translate("MainWindow", "Personel", None))
        self.radio_bolum.setText(_translate("MainWindow", "Bölüm", None))
        self.radio_kamera.setText(_translate("MainWindow", "Kamera", None))
        self.radio_okuyucu.setText(_translate("MainWindow", "Okuyucu", None))
        self.radio_ziyaretci.setText(_translate("MainWindow", "Ziyaretçi", None))
        self.groupBox_14.setTitle(_translate("MainWindow", "İzlemede", None))
        self.lbl_izlenen.setText(_translate("MainWindow", "<İzleme  Eklenmedi>", None))
        self.groupBox_13.setTitle(_translate("MainWindow", "Yakalanan", None))
        self.label_12.setText(_translate("MainWindow", "Kişi", None))
        self.label_13.setText(_translate("MainWindow", "Okuyucu", None))
        self.label_14.setText(_translate("MainWindow", "Kamera", None))
        self.label_16.setText(_translate("MainWindow", "Zaman ", None))
        self.lbl_durum.setText(_translate("MainWindow", "...", None))
        self.actionYukle.setText(_translate("MainWindow", "Yükle", None))

from pyqtgraph import PlotWidget
import a_rc
